Menu for create poll from wall stream
humhub/polls pull request #101
Opened 2022-08-18 15:33 UTC by yurabakhtin

Issue: https://github.com/humhub/team_tasks/issues/239

2022-08-28 15:13 UTC, luke- requested changes
We need to refactor this module a bit more.
There should be no longer an "Polls" menu entry with Pollls only stream etc.

2022-09-05 06:46 UTC, yurabakhtin commented on widgets/WallEntry.php
> +    public $menuIcon = 'bar-chart';
@luke- Yes, it was already done here https://github.com/humhub/polls/pull/101/commits/7a4d7da87d9b3f9a49debda47fea9093753a0f5f.

2022-09-05 06:51 UTC, yurabakhtin commented
@luke- 

> We need to refactor this module a bit more.
There should be no longer an "Polls" menu entry with Pollls only stream etc.

Ok, I will remove the "Polls" menu when I will find a solution for form on stream to make it work properly, because currently we have an issue with RichText on the loading form, it doesn't work for Post and Poll forms.

2022-09-08 07:10 UTC, yurabakhtin commented
@luke- 

> We need to refactor this module a bit more.
There should be no longer an "Polls" menu entry with Pollls only stream etc.

Commit https://github.com/humhub/polls/pull/101/commits/66f7f8c571bc55fd89a7ff083c88d35f5eebd493.

2022-09-12 16:46 UTC, luke- approved these changes

2022-11-07 16:20 UTC, luke- approved these changes

2022-11-07 16:20 UTC, merged